package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dia generated by hbm2java
 */
@Entity
@Table(name="dia"
    ,catalog="proyecto"
)
public class Dia  implements java.io.Serializable {


     private Integer idDias;
     private String diaSemana;
     private Set<MateriaHasHorario> materiaHasHorarios = new HashSet<MateriaHasHorario>(0);

    public Dia() {
    }

    public Dia(String diaSemana, Set<MateriaHasHorario> materiaHasHorarios) {
       this.diaSemana = diaSemana;
       this.materiaHasHorarios = materiaHasHorarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDias", unique=true, nullable=false)
    public Integer getIdDias() {
        return this.idDias;
    }
    
    public void setIdDias(Integer idDias) {
        this.idDias = idDias;
    }

    
    @Column(name="dia_semana", length=45)
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dia")
    public Set<MateriaHasHorario> getMateriaHasHorarios() {
        return this.materiaHasHorarios;
    }
    
    public void setMateriaHasHorarios(Set<MateriaHasHorario> materiaHasHorarios) {
        this.materiaHasHorarios = materiaHasHorarios;
    }




}


