package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private Integer idDias;
     private String diaSemana;
     private Set<MateriaHasHorario> materiaHasHorarios = new HashSet<MateriaHasHorario>(0);

    public Dia() {
    }

    public Dia(String diaSemana, Set<MateriaHasHorario> materiaHasHorarios) {
       this.diaSemana = diaSemana;
       this.materiaHasHorarios = materiaHasHorarios;
    }
   
    public Integer getIdDias() {
        return this.idDias;
    }
    
    public void setIdDias(Integer idDias) {
        this.idDias = idDias;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Set<MateriaHasHorario> getMateriaHasHorarios() {
        return this.materiaHasHorarios;
    }
    
    public void setMateriaHasHorarios(Set<MateriaHasHorario> materiaHasHorarios) {
        this.materiaHasHorarios = materiaHasHorarios;
    }




}


