package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer idDocente;
     private String nombre;
     private String apellido;
     private String cedulaDocente;
     private Set<MateriaHasDocente> materiaHasDocentes = new HashSet<MateriaHasDocente>(0);

    public Docente() {
    }

    public Docente(String nombre, String apellido, String cedulaDocente, Set<MateriaHasDocente> materiaHasDocentes) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedulaDocente = cedulaDocente;
       this.materiaHasDocentes = materiaHasDocentes;
    }
   
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedulaDocente() {
        return this.cedulaDocente;
    }
    
    public void setCedulaDocente(String cedulaDocente) {
        this.cedulaDocente = cedulaDocente;
    }
    public Set<MateriaHasDocente> getMateriaHasDocentes() {
        return this.materiaHasDocentes;
    }
    
    public void setMateriaHasDocentes(Set<MateriaHasDocente> materiaHasDocentes) {
        this.materiaHasDocentes = materiaHasDocentes;
    }




}


