package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="docente"
    ,catalog="proyecto"
)
public class Docente  implements java.io.Serializable {


     private Integer idDocente;
     private String nombre;
     private String apellido;
     private String cedulaDocente;
     private Set<MateriaHasDocente> materiaHasDocentes = new HashSet<MateriaHasDocente>(0);

    public Docente() {
    }

    public Docente(String nombre, String apellido, String cedulaDocente, Set<MateriaHasDocente> materiaHasDocentes) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedulaDocente = cedulaDocente;
       this.materiaHasDocentes = materiaHasDocentes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDocente", unique=true, nullable=false)
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="cedula_docente", length=10)
    public String getCedulaDocente() {
        return this.cedulaDocente;
    }
    
    public void setCedulaDocente(String cedulaDocente) {
        this.cedulaDocente = cedulaDocente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docente")
    public Set<MateriaHasDocente> getMateriaHasDocentes() {
        return this.materiaHasDocentes;
    }
    
    public void setMateriaHasDocentes(Set<MateriaHasDocente> materiaHasDocentes) {
        this.materiaHasDocentes = materiaHasDocentes;
    }




}


