package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * EquipoInformatico generated by hbm2java
 */
public class EquipoInformatico  implements java.io.Serializable {


     private Integer idEquipoInformatico;
     private Espacio espacio;
     private String nombre;
     private String descripcion;

    public EquipoInformatico() {
    }

    public EquipoInformatico(Espacio espacio, String nombre, String descripcion) {
       this.espacio = espacio;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public Integer getIdEquipoInformatico() {
        return this.idEquipoInformatico;
    }
    
    public void setIdEquipoInformatico(Integer idEquipoInformatico) {
        this.idEquipoInformatico = idEquipoInformatico;
    }
    public Espacio getEspacio() {
        return this.espacio;
    }
    
    public void setEspacio(Espacio espacio) {
        this.espacio = espacio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


