package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Espacio generated by hbm2java
 */
public class Espacio  implements java.io.Serializable {


     private Integer idEspacio;
     private Normativa normativa;
     private Tipo tipo;
     private String nombreEspacio;
     private Integer capacidad;
     private String iluminacion;
     private String internet;
     private Integer nrescritorios;
     private Set<EquipoInformatico> equipoInformaticos = new HashSet<EquipoInformatico>(0);
     private Set<EspacioHasMateria> espacioHasMaterias = new HashSet<EspacioHasMateria>(0);

    public Espacio() {
    }

	
    public Espacio(Tipo tipo) {
        this.tipo = tipo;
    }
    public Espacio(Normativa normativa, Tipo tipo, String nombreEspacio, Integer capacidad, String iluminacion, String internet, Integer nrescritorios, Set<EquipoInformatico> equipoInformaticos, Set<EspacioHasMateria> espacioHasMaterias) {
       this.normativa = normativa;
       this.tipo = tipo;
       this.nombreEspacio = nombreEspacio;
       this.capacidad = capacidad;
       this.iluminacion = iluminacion;
       this.internet = internet;
       this.nrescritorios = nrescritorios;
       this.equipoInformaticos = equipoInformaticos;
       this.espacioHasMaterias = espacioHasMaterias;
    }
   
    public Integer getIdEspacio() {
        return this.idEspacio;
    }
    
    public void setIdEspacio(Integer idEspacio) {
        this.idEspacio = idEspacio;
    }
    public Normativa getNormativa() {
        return this.normativa;
    }
    
    public void setNormativa(Normativa normativa) {
        this.normativa = normativa;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNombreEspacio() {
        return this.nombreEspacio;
    }
    
    public void setNombreEspacio(String nombreEspacio) {
        this.nombreEspacio = nombreEspacio;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public String getIluminacion() {
        return this.iluminacion;
    }
    
    public void setIluminacion(String iluminacion) {
        this.iluminacion = iluminacion;
    }
    public String getInternet() {
        return this.internet;
    }
    
    public void setInternet(String internet) {
        this.internet = internet;
    }
    public Integer getNrescritorios() {
        return this.nrescritorios;
    }
    
    public void setNrescritorios(Integer nrescritorios) {
        this.nrescritorios = nrescritorios;
    }
    public Set<EquipoInformatico> getEquipoInformaticos() {
        return this.equipoInformaticos;
    }
    
    public void setEquipoInformaticos(Set<EquipoInformatico> equipoInformaticos) {
        this.equipoInformaticos = equipoInformaticos;
    }
    public Set<EspacioHasMateria> getEspacioHasMaterias() {
        return this.espacioHasMaterias;
    }
    
    public void setEspacioHasMaterias(Set<EspacioHasMateria> espacioHasMaterias) {
        this.espacioHasMaterias = espacioHasMaterias;
    }




}


