package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * EspacioHasMateria generated by hbm2java
 */
public class EspacioHasMateria  implements java.io.Serializable {


     private EspacioHasMateriaId id;
     private Espacio espacio;
     private Materia materia;
     private String periodo;

    public EspacioHasMateria() {
    }

	
    public EspacioHasMateria(EspacioHasMateriaId id, Espacio espacio, Materia materia) {
        this.id = id;
        this.espacio = espacio;
        this.materia = materia;
    }
    public EspacioHasMateria(EspacioHasMateriaId id, Espacio espacio, Materia materia, String periodo) {
       this.id = id;
       this.espacio = espacio;
       this.materia = materia;
       this.periodo = periodo;
    }
   
    public EspacioHasMateriaId getId() {
        return this.id;
    }
    
    public void setId(EspacioHasMateriaId id) {
        this.id = id;
    }
    public Espacio getEspacio() {
        return this.espacio;
    }
    
    public void setEspacio(Espacio espacio) {
        this.espacio = espacio;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


