package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EspacioHasMateriaId generated by hbm2java
 */
@Embeddable
public class EspacioHasMateriaId  implements java.io.Serializable {


     private int espacioIdEspacio;
     private int materiaIdMateria;

    public EspacioHasMateriaId() {
    }

    public EspacioHasMateriaId(int espacioIdEspacio, int materiaIdMateria) {
       this.espacioIdEspacio = espacioIdEspacio;
       this.materiaIdMateria = materiaIdMateria;
    }
   


    @Column(name="Espacio_idEspacio", nullable=false)
    public int getEspacioIdEspacio() {
        return this.espacioIdEspacio;
    }
    
    public void setEspacioIdEspacio(int espacioIdEspacio) {
        this.espacioIdEspacio = espacioIdEspacio;
    }


    @Column(name="materia_idMateria", nullable=false)
    public int getMateriaIdMateria() {
        return this.materiaIdMateria;
    }
    
    public void setMateriaIdMateria(int materiaIdMateria) {
        this.materiaIdMateria = materiaIdMateria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EspacioHasMateriaId) ) return false;
		 EspacioHasMateriaId castOther = ( EspacioHasMateriaId ) other; 
         
		 return (this.getEspacioIdEspacio()==castOther.getEspacioIdEspacio())
 && (this.getMateriaIdMateria()==castOther.getMateriaIdMateria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEspacioIdEspacio();
         result = 37 * result + this.getMateriaIdMateria();
         return result;
   }   


}


