package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idEstudiante;
     private String nombre;
     private String apellido;
     private String carrera;
     private String cedula;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Estudiante() {
    }

    public Estudiante(String nombre, String apellido, String carrera, String cedula, Set<Matricula> matriculas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.carrera = carrera;
       this.cedula = cedula;
       this.matriculas = matriculas;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


