package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name="estudiante"
    ,catalog="proyecto"
)
public class Estudiante  implements java.io.Serializable {


     private Integer idEstudiante;
     private String nombre;
     private String apellido;
     private String carrera;
     private String cedula;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Estudiante() {
    }

    public Estudiante(String nombre, String apellido, String carrera, String cedula, Set<Matricula> matriculas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.carrera = carrera;
       this.cedula = cedula;
       this.matriculas = matriculas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEstudiante", unique=true, nullable=false)
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="carrera", length=45)
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }

    
    @Column(name="cedula", length=10)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


