package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formula generated by hbm2java
 */
@Entity
@Table(name="formula"
    ,catalog="proyecto"
)
public class Formula  implements java.io.Serializable {


     private Integer idFormula;
     private String nombre;
     private String formula;
     private String descripcion;
     private Set<Normativa> normativas = new HashSet<Normativa>(0);

    public Formula() {
    }

    public Formula(String nombre, String formula, String descripcion, Set<Normativa> normativas) {
       this.nombre = nombre;
       this.formula = formula;
       this.descripcion = descripcion;
       this.normativas = normativas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFormula", unique=true, nullable=false)
    public Integer getIdFormula() {
        return this.idFormula;
    }
    
    public void setIdFormula(Integer idFormula) {
        this.idFormula = idFormula;
    }

    
    @Column(name="Nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Formula", length=90)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }

    
    @Column(name="Descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formula")
    public Set<Normativa> getNormativas() {
        return this.normativas;
    }
    
    public void setNormativas(Set<Normativa> normativas) {
        this.normativas = normativas;
    }




}


