package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="horario"
    ,catalog="proyecto"
)
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private String horaInicio;
     private String horaFinal;
     private Set<MateriaHasHorario> materiaHasHorarios = new HashSet<MateriaHasHorario>(0);

    public Horario() {
    }

    public Horario(String horaInicio, String horaFinal, Set<MateriaHasHorario> materiaHasHorarios) {
       this.horaInicio = horaInicio;
       this.horaFinal = horaFinal;
       this.materiaHasHorarios = materiaHasHorarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHorario", unique=true, nullable=false)
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    
    @Column(name="hora_inicio", length=45)
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }

    
    @Column(name="hora_final", length=45)
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horario")
    public Set<MateriaHasHorario> getMateriaHasHorarios() {
        return this.materiaHasHorarios;
    }
    
    public void setMateriaHasHorarios(Set<MateriaHasHorario> materiaHasHorarios) {
        this.materiaHasHorarios = materiaHasHorarios;
    }




}


