package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * MateriaHasHorario generated by hbm2java
 */
public class MateriaHasHorario  implements java.io.Serializable {


     private MateriaHasHorarioId id;
     private Dia dia;
     private Horario horario;
     private Materia materia;
     private String periodo;

    public MateriaHasHorario() {
    }

	
    public MateriaHasHorario(MateriaHasHorarioId id, Dia dia, Horario horario, Materia materia) {
        this.id = id;
        this.dia = dia;
        this.horario = horario;
        this.materia = materia;
    }
    public MateriaHasHorario(MateriaHasHorarioId id, Dia dia, Horario horario, Materia materia, String periodo) {
       this.id = id;
       this.dia = dia;
       this.horario = horario;
       this.materia = materia;
       this.periodo = periodo;
    }
   
    public MateriaHasHorarioId getId() {
        return this.id;
    }
    
    public void setId(MateriaHasHorarioId id) {
        this.id = id;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


