package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name="materia"
    ,catalog="proyecto"
)
public class Materia  implements java.io.Serializable {


     private Integer idMateria;
     private String nombre;
     private String descripcion;
     private Set<EspacioHasMateria> espacioHasMaterias = new HashSet<EspacioHasMateria>(0);
     private Set<MateriaHasHorario> materiaHasHorarios = new HashSet<MateriaHasHorario>(0);
     private Set<MatriculaHasMateria> matriculaHasMaterias = new HashSet<MatriculaHasMateria>(0);
     private Set<MateriaHasDocente> materiaHasDocentes = new HashSet<MateriaHasDocente>(0);

    public Materia() {
    }

    public Materia(String nombre, String descripcion, Set<EspacioHasMateria> espacioHasMaterias, Set<MateriaHasHorario> materiaHasHorarios, Set<MatriculaHasMateria> matriculaHasMaterias, Set<MateriaHasDocente> materiaHasDocentes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.espacioHasMaterias = espacioHasMaterias;
       this.materiaHasHorarios = materiaHasHorarios;
       this.matriculaHasMaterias = matriculaHasMaterias;
       this.materiaHasDocentes = materiaHasDocentes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMateria", unique=true, nullable=false)
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set<EspacioHasMateria> getEspacioHasMaterias() {
        return this.espacioHasMaterias;
    }
    
    public void setEspacioHasMaterias(Set<EspacioHasMateria> espacioHasMaterias) {
        this.espacioHasMaterias = espacioHasMaterias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set<MateriaHasHorario> getMateriaHasHorarios() {
        return this.materiaHasHorarios;
    }
    
    public void setMateriaHasHorarios(Set<MateriaHasHorario> materiaHasHorarios) {
        this.materiaHasHorarios = materiaHasHorarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set<MatriculaHasMateria> getMatriculaHasMaterias() {
        return this.matriculaHasMaterias;
    }
    
    public void setMatriculaHasMaterias(Set<MatriculaHasMateria> matriculaHasMaterias) {
        this.matriculaHasMaterias = matriculaHasMaterias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set<MateriaHasDocente> getMateriaHasDocentes() {
        return this.materiaHasDocentes;
    }
    
    public void setMateriaHasDocentes(Set<MateriaHasDocente> materiaHasDocentes) {
        this.materiaHasDocentes = materiaHasDocentes;
    }




}


