package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MateriaHasDocente generated by hbm2java
 */
@Entity
@Table(name="materia_has_docente"
    ,catalog="proyecto"
)
public class MateriaHasDocente  implements java.io.Serializable {


     private MateriaHasDocenteId id;
     private Docente docente;
     private Materia materia;
     private String periodo;

    public MateriaHasDocente() {
    }

	
    public MateriaHasDocente(MateriaHasDocenteId id, Docente docente, Materia materia) {
        this.id = id;
        this.docente = docente;
        this.materia = materia;
    }
    public MateriaHasDocente(MateriaHasDocenteId id, Docente docente, Materia materia, String periodo) {
       this.id = id;
       this.docente = docente;
       this.materia = materia;
       this.periodo = periodo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="materiaIdMateria", column=@Column(name="materia_idMateria", nullable=false) ), 
        @AttributeOverride(name="docenteIdDocente", column=@Column(name="docente_idDocente", nullable=false) ) } )
    public MateriaHasDocenteId getId() {
        return this.id;
    }
    
    public void setId(MateriaHasDocenteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="docente_idDocente", nullable=false, insertable=false, updatable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="materia_idMateria", nullable=false, insertable=false, updatable=false)
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    
    @Column(name="periodo", length=45)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


