package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * MateriaHasHorarioId generated by hbm2java
 */
public class MateriaHasHorarioId  implements java.io.Serializable {


     private int materiaIdMateria;
     private int horarioIdHorario;
     private int diaIdDias;

    public MateriaHasHorarioId() {
    }

    public MateriaHasHorarioId(int materiaIdMateria, int horarioIdHorario, int diaIdDias) {
       this.materiaIdMateria = materiaIdMateria;
       this.horarioIdHorario = horarioIdHorario;
       this.diaIdDias = diaIdDias;
    }
   
    public int getMateriaIdMateria() {
        return this.materiaIdMateria;
    }
    
    public void setMateriaIdMateria(int materiaIdMateria) {
        this.materiaIdMateria = materiaIdMateria;
    }
    public int getHorarioIdHorario() {
        return this.horarioIdHorario;
    }
    
    public void setHorarioIdHorario(int horarioIdHorario) {
        this.horarioIdHorario = horarioIdHorario;
    }
    public int getDiaIdDias() {
        return this.diaIdDias;
    }
    
    public void setDiaIdDias(int diaIdDias) {
        this.diaIdDias = diaIdDias;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MateriaHasHorarioId) ) return false;
		 MateriaHasHorarioId castOther = ( MateriaHasHorarioId ) other; 
         
		 return (this.getMateriaIdMateria()==castOther.getMateriaIdMateria())
 && (this.getHorarioIdHorario()==castOther.getHorarioIdHorario())
 && (this.getDiaIdDias()==castOther.getDiaIdDias());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMateriaIdMateria();
         result = 37 * result + this.getHorarioIdHorario();
         result = 37 * result + this.getDiaIdDias();
         return result;
   }   


}


