package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MateriaHasHorario generated by hbm2java
 */
@Entity
@Table(name="materia_has_horario"
    ,catalog="proyecto"
)
public class MateriaHasHorario  implements java.io.Serializable {


     private MateriaHasHorarioId id;
     private Dia dia;
     private Horario horario;
     private Materia materia;
     private String periodo;

    public MateriaHasHorario() {
    }

	
    public MateriaHasHorario(MateriaHasHorarioId id, Dia dia, Horario horario, Materia materia) {
        this.id = id;
        this.dia = dia;
        this.horario = horario;
        this.materia = materia;
    }
    public MateriaHasHorario(MateriaHasHorarioId id, Dia dia, Horario horario, Materia materia, String periodo) {
       this.id = id;
       this.dia = dia;
       this.horario = horario;
       this.materia = materia;
       this.periodo = periodo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="materiaIdMateria", column=@Column(name="materia_idMateria", nullable=false) ), 
        @AttributeOverride(name="horarioIdHorario", column=@Column(name="horario_idHorario", nullable=false) ), 
        @AttributeOverride(name="diaIdDias", column=@Column(name="dia_idDias", nullable=false) ) } )
    public MateriaHasHorarioId getId() {
        return this.id;
    }
    
    public void setId(MateriaHasHorarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dia_idDias", nullable=false, insertable=false, updatable=false)
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="horario_idHorario", nullable=false, insertable=false, updatable=false)
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="materia_idMateria", nullable=false, insertable=false, updatable=false)
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    
    @Column(name="periodo", length=45)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


