package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * MateriaHasDocente generated by hbm2java
 */
public class MateriaHasDocente  implements java.io.Serializable {


     private MateriaHasDocenteId id;
     private Docente docente;
     private Materia materia;
     private String periodo;

    public MateriaHasDocente() {
    }

	
    public MateriaHasDocente(MateriaHasDocenteId id, Docente docente, Materia materia) {
        this.id = id;
        this.docente = docente;
        this.materia = materia;
    }
    public MateriaHasDocente(MateriaHasDocenteId id, Docente docente, Materia materia, String periodo) {
       this.id = id;
       this.docente = docente;
       this.materia = materia;
       this.periodo = periodo;
    }
   
    public MateriaHasDocenteId getId() {
        return this.id;
    }
    
    public void setId(MateriaHasDocenteId id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


