package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Integer idMatricula;
     private Estudiante estudiante;
     private String periodo;
     private String observacion;
     private Set<MatriculaHasMateria> matriculaHasMaterias = new HashSet<MatriculaHasMateria>(0);

    public Matricula() {
    }

	
    public Matricula(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Matricula(Estudiante estudiante, String periodo, String observacion, Set<MatriculaHasMateria> matriculaHasMaterias) {
       this.estudiante = estudiante;
       this.periodo = periodo;
       this.observacion = observacion;
       this.matriculaHasMaterias = matriculaHasMaterias;
    }
   
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set<MatriculaHasMateria> getMatriculaHasMaterias() {
        return this.matriculaHasMaterias;
    }
    
    public void setMatriculaHasMaterias(Set<MatriculaHasMateria> matriculaHasMaterias) {
        this.matriculaHasMaterias = matriculaHasMaterias;
    }




}


