package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1



/**
 * MatriculaHasMateria generated by hbm2java
 */
public class MatriculaHasMateria  implements java.io.Serializable {


     private MatriculaHasMateriaId id;
     private Materia materia;
     private Matricula matricula;
     private String periodo;

    public MatriculaHasMateria() {
    }

	
    public MatriculaHasMateria(MatriculaHasMateriaId id, Materia materia, Matricula matricula) {
        this.id = id;
        this.materia = materia;
        this.matricula = matricula;
    }
    public MatriculaHasMateria(MatriculaHasMateriaId id, Materia materia, Matricula matricula, String periodo) {
       this.id = id;
       this.materia = materia;
       this.matricula = matricula;
       this.periodo = periodo;
    }
   
    public MatriculaHasMateriaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaHasMateriaId id) {
        this.id = id;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


