package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatriculaHasMateriaId generated by hbm2java
 */
@Embeddable
public class MatriculaHasMateriaId  implements java.io.Serializable {


     private int matriculaIdMatricula;
     private int materiaIdMateria;

    public MatriculaHasMateriaId() {
    }

    public MatriculaHasMateriaId(int matriculaIdMatricula, int materiaIdMateria) {
       this.matriculaIdMatricula = matriculaIdMatricula;
       this.materiaIdMateria = materiaIdMateria;
    }
   


    @Column(name="matricula_idMatricula", nullable=false)
    public int getMatriculaIdMatricula() {
        return this.matriculaIdMatricula;
    }
    
    public void setMatriculaIdMatricula(int matriculaIdMatricula) {
        this.matriculaIdMatricula = matriculaIdMatricula;
    }


    @Column(name="materia_idMateria", nullable=false)
    public int getMateriaIdMateria() {
        return this.materiaIdMateria;
    }
    
    public void setMateriaIdMateria(int materiaIdMateria) {
        this.materiaIdMateria = materiaIdMateria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaHasMateriaId) ) return false;
		 MatriculaHasMateriaId castOther = ( MatriculaHasMateriaId ) other; 
         
		 return (this.getMatriculaIdMatricula()==castOther.getMatriculaIdMatricula())
 && (this.getMateriaIdMateria()==castOther.getMateriaIdMateria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMatriculaIdMatricula();
         result = 37 * result + this.getMateriaIdMateria();
         return result;
   }   


}


