package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Normativa generated by hbm2java
 */
@Entity
@Table(name="normativa"
    ,catalog="proyecto"
)
public class Normativa  implements java.io.Serializable {


     private Integer idNormativa;
     private Formula formula;
     private Integer funcionalidad;
     private Integer equipamiento;
     private Integer disponibilidad;
     private Set<Espacio> espacios = new HashSet<Espacio>(0);

    public Normativa() {
    }

	
    public Normativa(Formula formula) {
        this.formula = formula;
    }
    public Normativa(Formula formula, Integer funcionalidad, Integer equipamiento, Integer disponibilidad, Set<Espacio> espacios) {
       this.formula = formula;
       this.funcionalidad = funcionalidad;
       this.equipamiento = equipamiento;
       this.disponibilidad = disponibilidad;
       this.espacios = espacios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idNormativa", unique=true, nullable=false)
    public Integer getIdNormativa() {
        return this.idNormativa;
    }
    
    public void setIdNormativa(Integer idNormativa) {
        this.idNormativa = idNormativa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="formula_idFormula", nullable=false)
    public Formula getFormula() {
        return this.formula;
    }
    
    public void setFormula(Formula formula) {
        this.formula = formula;
    }

    
    @Column(name="funcionalidad")
    public Integer getFuncionalidad() {
        return this.funcionalidad;
    }
    
    public void setFuncionalidad(Integer funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

    
    @Column(name="equipamiento")
    public Integer getEquipamiento() {
        return this.equipamiento;
    }
    
    public void setEquipamiento(Integer equipamiento) {
        this.equipamiento = equipamiento;
    }

    
    @Column(name="disponibilidad")
    public Integer getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Integer disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="normativa")
    public Set<Espacio> getEspacios() {
        return this.espacios;
    }
    
    public void setEspacios(Set<Espacio> espacios) {
        this.espacios = espacios;
    }




}


