package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Normativa generated by hbm2java
 */
public class Normativa  implements java.io.Serializable {


     private Integer idNormativa;
     private Formula formula;
     private Integer funcionalidad;
     private Integer equipamiento;
     private Integer disponibilidad;
     private Set<Espacio> espacios = new HashSet<Espacio>(0);

    public Normativa() {
    }

	
    public Normativa(Formula formula) {
        this.formula = formula;
    }
    public Normativa(Formula formula, Integer funcionalidad, Integer equipamiento, Integer disponibilidad, Set<Espacio> espacios) {
       this.formula = formula;
       this.funcionalidad = funcionalidad;
       this.equipamiento = equipamiento;
       this.disponibilidad = disponibilidad;
       this.espacios = espacios;
    }
   
    public Integer getIdNormativa() {
        return this.idNormativa;
    }
    
    public void setIdNormativa(Integer idNormativa) {
        this.idNormativa = idNormativa;
    }
    public Formula getFormula() {
        return this.formula;
    }
    
    public void setFormula(Formula formula) {
        this.formula = formula;
    }
    public Integer getFuncionalidad() {
        return this.funcionalidad;
    }
    
    public void setFuncionalidad(Integer funcionalidad) {
        this.funcionalidad = funcionalidad;
    }
    public Integer getEquipamiento() {
        return this.equipamiento;
    }
    
    public void setEquipamiento(Integer equipamiento) {
        this.equipamiento = equipamiento;
    }
    public Integer getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Integer disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public Set<Espacio> getEspacios() {
        return this.espacios;
    }
    
    public void setEspacios(Set<Espacio> espacios) {
        this.espacios = espacios;
    }




}


