package com.proyecto.modelo;
// Generated 26/07/2017 14:26:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private Integer idTipo;
     private String nombre;
     private Set<Espacio> espacios = new HashSet<Espacio>(0);

    public Tipo() {
    }

    public Tipo(String nombre, Set<Espacio> espacios) {
       this.nombre = nombre;
       this.espacios = espacios;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Espacio> getEspacios() {
        return this.espacios;
    }
    
    public void setEspacios(Set<Espacio> espacios) {
        this.espacios = espacios;
    }




}


