package com.proyecto.modelo;
// Generated 27/07/2017 15:17:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="tipo"
    ,catalog="proyecto"
)
public class Tipo  implements java.io.Serializable {


     private Integer idTipo;
     private String nombre;
     private Set<Espacio> espacios = new HashSet<Espacio>(0);

    public Tipo() {
    }

    public Tipo(String nombre, Set<Espacio> espacios) {
       this.nombre = nombre;
       this.espacios = espacios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipo", unique=true, nullable=false)
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipo")
    public Set<Espacio> getEspacios() {
        return this.espacios;
    }
    
    public void setEspacios(Set<Espacio> espacios) {
        this.espacios = espacios;
    }




}


